Source  = \
	DataArray.java \
	DoubleList.java \
	FloatList.java \
	Formatter.java \
	Indentation.java \
	IntList.java \
	ISO8601DateParser.java \
	JsonUtil.java \
	RunningPercentile.java \
	Util.java \

include $(DEV_HOME)/jtimeseries/Makefile
