Source = \
	JsonTimeSeries.java \
	JsonTimeSeriesDataListener.java \
	JsonTimeSeriesReader.java \
	JsonTimeSeriesUtil.java \
	JsonTimeSeriesWriter.java \
	Signal.java \
	ValueType.java \
	WellKnownProperty.java \

Main = Signal

include $(DEV_HOME)/timeseries-io/java/Makefile