Source = \
	Signal.java \
	TimeSeriesJson.java \
	TimeSeriesJsonDataListener.java \
	TimeSeriesJsonReader.java \
	TimeSeriesJsonUtil.java \
	TimeSeriesJsonWriter.java \
	ValueType.java \
	WellKnownProperty.java \

Main = TimeSeriesJson

include $(DEV_HOME)/timeseries-io/java/Makefile