Source = \
	Signal.java \
	Statistics.java \
	TimeSeries.java \
	TimeSeriesDataListener.java \
	TimeSeriesReader.java \
	TimeSeriesUtil.java \
	TimeSeriesWriter.java \
	ValueType.java \
	WellKnownProperty.java \

Main = TimeSeriesReader

include $(DEV_HOME)/jtimeseries/Makefile