Source = \
	JsonUtil.java \
	JsonWellLogFormatSchema.java \
	Signal.java \
	Statistics.java \
	TimeSeries.java \
	TimeSeriesDataListener.java \
	TimeSeriesReader.java \
	TimeSeriesWriter.java \
	units.txt \
	Util.java \
	ValueType.java \
	WellKnownProperty.java \

include $(DEV_HOME)/jtimeseries/Makefile