Source = \
	GpxReader.java \
	Signal.java \
	Statistics.java \
	TimeSeries.java \
	TimeSeriesDataListener.java \
	TimeSeriesReader.java \
	TimeSeriesUtil.java \
	TimeSeriesWriter.java \
	ValueType.java \
	WellKnownProperty.java \
	NewYorkCityMarathon.gpx \

Main = TimeSeries

include $(DEV_HOME)/jtimeseries/Makefile